import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import {effective,ratio,fuente as framingSource} from '../services/framing.js';
export const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const price=p=>p.precio===null?'Consultar':`G$ ${new Intl.NumberFormat('es-PY').format(p.precio)}${p.por_kg?' / kg':''}`;
const data=async(file,type)=>`data:${type};base64,${(await fs.readFile(file)).toString('base64')}`;
const mobilePhoto=async(file)=>'data:image/jpeg;base64,'+(await sharp(file).resize({width:1100,height:1100,fit:'inside',withoutEnlargement:true}).jpeg({quality:80,mozjpeg:true}).toBuffer()).toString('base64');
export async function template(snapshot,options,cfg,images){const base=path.join(cfg.publicDir,'assets');const font=async name=>data(path.join(base,'fonts',name),'font/woff2');const css=await fs.readFile(new URL('./styles.css',import.meta.url),'utf8');const [spectral,body,bold,hero,logo]=await Promise.all([font('spectral-latin-400-normal.woff2'),font('hanken-grotesk-latin-400-normal.woff2'),font('hanken-grotesk-latin-600-normal.woff2'),data(path.join(base,'img/hero.webp'),'image/webp'),data(path.join(base,'logo/silos-paraguay-claro.png'),'image/png')]);
  const date=new Intl.DateTimeFormat('es-PY',{month:'long',year:'numeric',timeZone:'America/Asuncion'}).format(new Date());
  // El encuadre viaja como dato: apply-framing.js lo aplica midiendo el recuadro
  // real de cada ficha. Si no llega a correr, el CSS deja la foto entera y centrada.
  const framing=(id)=>{const row=images.row(id);const f=row&&effective(row.metadata);return f?` data-frame="${[f.x,f.y,f.w,f.h,ratio(row.metadata)].map(n=>n.toFixed(6)).join(' ')}"`:'';};
  const cards=[];for(const p of snapshot.items){const photo=p.imagen_id?await mobilePhoto(await images.ensure(p.imagen_id,'pdf')):null;cards.push(`<article class="card" data-category="${esc(p.categoria)}" data-product-id="${p.id}"><div class="photo">${photo?`<img${framing(p.imagen_id)} src="${photo}" alt="${esc(p.producto)}">`:'<span class="no-photo">Imagen próximamente</span>'}${!p.stock?`<span class="stock">${p.stock===null?'Consultar disponibilidad':'Sin stock'}</span>`:''}</div><p class="brand">${esc(p.marca||p.origen)}</p><h2>${esc(p.producto)}</h2><p class="presentation">${esc(p.presentacion)}</p>${p.marca&&p.origen?`<p class="origin">${esc(p.origen)}</p>`:''}${p.notas?`<p class="note">${esc(p.notas)}</p>`:''}${options.includePrices?`<p class="price">${price(p)}</p>`:''}</article>`);}
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><title>Silos Paraguay · Catálogo móvil · r${snapshot.settings.revision}</title><style>@font-face{font-family:Spectral;src:url('${spectral}')}@font-face{font-family:Hanken;src:url('${body}')}@font-face{font-family:Hanken;src:url('${bold}');font-weight:600}${css}</style><script>${framingSource}</script></head><body><section class="pdf-page cover"><div class="cover-image" style="background-image:url('${hero}')"></div><div class="cover-content"><img class="logo" src="${logo}" alt="Silos Paraguay"><p class="eyebrow">CATÁLOGO · ${esc(date)}</p><h1>Selección<br>de Europa</h1><p class="cover-sub">Quesos, jamones y fiambres.</p><p class="cover-foot">Respeto. Calidad. Sabor.</p></div></section><div id="pages"></div><section class="pdf-page closing"><img class="logo" src="${logo}" alt="Silos Paraguay"><p class="eyebrow">DE EUROPA A TU NEGOCIO</p><h1>Hablemos<br>de cosas ricas.</h1><p>Una selección de quesos, jamones y fiambres para tu góndola y tu cocina.</p><div class="contacts"><a href="mailto:jvanden@silospy.com">jvanden@silospy.com</a><a href="tel:+595981630931">+595 981 630 931</a><a href="mailto:cecierbin@silospy.com">cecierbin@silospy.com</a><a href="tel:+595994703334">+595 994 703 334</a></div><a class="catalog-link" href="${esc(cfg.origin)}/catalogo.html">Ver catálogo online ↗</a>${options.includePrices?'<p class="legal">Precios de referencia en guaraníes, sujetos a cambio sin previo aviso.</p>':''}<p class="edition">${esc(date)} · Edición ${snapshot.settings.revision}</p></section><div id="source">${cards.join('')}</div></body></html>`;
}
