import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import {randomUUID,randomBytes} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import argon2 from 'argon2';
import sharp from 'sharp';
import {config,ROOT} from '../../server/config.js';
import {createApp} from '../../server/app.js';
import {defaults} from '../../server/services/catalog.js';
import {backup,restore} from '../../server/services/backup.js';
import {hash} from '../../server/services/images.js';
const tempRoot=path.join(ROOT,'tmp/tests');fs.mkdirSync(tempRoot,{recursive:true});
const adminHash=await argon2.hash('Prueba-local-12345');
async function fixture(t,options={}){const cfg=config({dataDir:fs.mkdtempSync(path.join(tempRoot,'run-')),secret:'test-only-secret-32-characters-minimum',quota:1024**3,production:false,origin:'http://127.0.0.1'});const ctx=createApp(cfg,options);ctx.db.prepare('INSERT INTO admins(id,usuario,password_hash) VALUES(?,?,?)').run('test-admin','prueba',adminHash);const server=ctx.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));cfg.origin='http://127.0.0.1:'+server.address().port;t.after(async()=>{await new Promise(r=>server.close(r));ctx.close();});
  function client(){let cookie='',csrf='';return {async request(url,{method='GET',body,form,headers={},token=true,origin=cfg.origin}={}){const r=await fetch(cfg.origin+url,{method,headers:{...(cookie?{Cookie:cookie}:{}),Origin:origin,...(method!=='GET'&&token?{'X-CSRF-Token':csrf}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{}),...headers},body:form|| (body===undefined?undefined:JSON.stringify(body))});const set=r.headers.getSetCookie();if(set.length)cookie=set[0].split(';')[0];const type=r.headers.get('content-type')||'';const data=type.includes('application/json')?await r.json():await r.arrayBuffer();if(data.csrf)csrf=data.csrf;return {status:r.status,data,headers:r.headers};},async login(){await this.request('/api/auth/session');return this.request('/api/auth/login',{method:'POST',body:{usuario:'prueba',password:'Prueba-local-12345'}});}};}
  return {...ctx,cfg,client};}
const item=(name,extra={})=>({...defaults,producto:name,visible:true,stock:true,...extra});
test('producto de foto suelta: disponibilidad desconocida, sin inventar precio o gramaje',async t=>{
  const f=await fixture(t);let p=f.catalog.save(null,item('Basiron',{stock:null,precio:null,presentacion:''}));
  assert.equal(f.catalog.publicCatalog().items[0].stock,null);assert.equal(f.catalog.list({status:'nostock'}).total,0);assert.equal(f.catalog.list({}).counts.noStock,0);
  p=f.catalog.save(p.id,{notas:'Editado'},p.version);assert.equal(p.stock,null);
  p=f.catalog.save(p.id,{stock:true},p.version);assert.equal(p.stock,true);
  p=f.catalog.save(p.id,{stock:null},p.version);assert.equal(p.stock,null);
});
const photo=async()=>sharp({create:{width:800,height:600,channels:4,background:{r:180,g:80,b:30,alpha:.5}}}).png().toBuffer();

test('sesión real, CSRF, cierre y rutas privadas no estáticas',async t=>{const f=await fixture(t),c=f.client();assert.equal((await c.request('/api/admin/products')).status,401);await c.request('/api/auth/session');assert.equal((await c.request('/api/auth/login',{method:'POST',body:{usuario:'prueba',password:'cualquiera'}})).status,401);assert.equal((await c.login()).status,200);assert.equal((await c.request('/api/admin/products')).status,200);assert.equal((await c.request('/api/admin/products',{method:'POST',body:item('Queso'),token:false})).status,403);assert.equal((await c.request('/api/admin/products',{method:'POST',body:item('Queso'),origin:'https://otro.test'})).status,403);for(const p of ['/data/catalogo.json','/storage/catalog.sqlite','/output/PLAN-IMPLEMENTACION-SILOS.md','/.env','/server/app.js'])assert.equal((await c.request(p)).status,404);assert.equal((await c.request('/api/auth/logout',{method:'POST',body:{}})).status,200);assert.equal((await c.request('/api/admin/products')).status,401);});
test('precios omitidos, visibilidad y archivo; reglas independientes',async t=>{const f=await fixture(t);let p=f.catalog.save(null,item('Queso',{precio:42000,por_kg:true}));assert.ok(!('precio' in f.catalog.publicCatalog().items[0]));f.catalog.updateSettings({mostrar_precios:true},f.catalog.settings().revision);assert.equal(f.catalog.publicCatalog().items[0].precio,42000);assert.throws(()=>f.catalog.save(p.id,{mostrar_precio_web:false},p.version));f.catalog.updateSettings({mostrar_precios:false},f.catalog.settings().revision);assert.ok(!('precio' in f.catalog.publicCatalog().items[0]));p=f.catalog.save(p.id,{visible:false},p.version);assert.equal(f.catalog.publicCatalog().items.length,0);p=f.catalog.archive(p.id,p.version);p=f.catalog.archive(p.id,p.version,true);assert.equal(p.visible,false);assert.equal(p.archived_at,null);});
test('los 36 productos juntos; búsqueda y filtros sobre la lista completa',async t=>{const f=await fixture(t);for(let i=0;i<36;i++)f.catalog.save(null,item(i===35?'Jamón último':'Queso '+i,{orden:i}));assert.equal(f.catalog.list({}).items.length,36);assert.equal(f.catalog.list({q:'jamon'}).total,1);let p=f.catalog.list({q:'jamon'}).items[0];p=f.catalog.save(p.id,{stock:false},p.version);assert.equal(f.catalog.list({status:'nostock'}).items[0].id,p.id);f.catalog.archive(p.id,p.version);assert.equal(f.catalog.list({}).total,35);assert.equal(f.catalog.list({status:'archived'}).total,1);});

test('categorías: alta, nombres únicos, renombrado, orden y traslado atómico con archivados',async t=>{let fail=false;const f=await fixture(t,{fault:point=>{if(fail&&point==='beforeCategoryCommit')throw new Error('Fallo simulado');}});const category=c=>f.catalog.categories(c,f.catalog.settings().revision);category({action:'create',name:'Conservas'});assert.throws(()=>category({action:'create',name:'Cónservas'}),/existe/);let a=f.catalog.save(null,item('A',{categoria:'Conservas'})),b=f.catalog.save(null,item('B',{categoria:'Conservas'}));b=f.catalog.archive(b.id,b.version);category({action:'rename',name:'Conservas',newName:'Aceitunas'});assert.equal(f.catalog.get(a.id).categoria,'Aceitunas');assert.equal(f.catalog.get(b.id).categoria,'Aceitunas');assert.throws(()=>f.catalog.save(a.id,{stock:false},a.version),/otra ventana/);assert.throws(()=>category({action:'remove',name:'Aceitunas'}),/mover/);fail=true;assert.throws(()=>category({action:'remove',name:'Aceitunas',target:'Quesos'}));assert.equal(f.catalog.get(a.id).categoria,'Aceitunas');fail=false;category({action:'move',name:'Aceitunas',direction:'up'});assert.equal(f.catalog.settings().categories.at(-2),'Aceitunas');category({action:'remove',name:'Aceitunas',target:'Quesos'});assert.equal(f.catalog.get(b.id).categoria,'Quesos');assert.ok(!f.catalog.settings().categories.includes('Aceitunas'));assert.throws(()=>f.catalog.save(null,item('Inválido',{categoria:'Sin crear'})));});

test('categorías y ajustes requieren sesión/CSRF; destacados conservados al ocultar sección',async t=>{const f=await fixture(t),c=f.client();assert.equal((await c.request('/api/admin/categories',{method:'PUT',body:{}})).status,403);await c.login();const rev=f.catalog.settings().revision;assert.equal((await c.request('/api/admin/categories',{method:'PUT',body:{action:'create',name:'Nueva',revision:rev},token:false})).status,403);assert.equal((await c.request('/api/admin/categories',{method:'PUT',body:{action:'create',name:'Nueva',revision:rev}})).status,200);assert.equal((await c.request('/api/admin/categories',{method:'PUT',body:{action:'create',name:'Otra',revision:rev}})).status,409);const p=f.catalog.save(null,item('Destacado'));f.catalog.featured([p.id],f.catalog.settings().revision,false);assert.equal(f.catalog.publicCatalog().mostrar_destacados,false);assert.deepEqual(f.catalog.settings().featured,[p.id]);f.catalog.save(p.id,{stock:false},f.catalog.get(p.id).version);assert.equal(f.catalog.settings().mostrar_destacados,false);assert.ok(f.catalog.settings().categories.includes('Nueva'));f.catalog.updateSettings({mostrar_destacados:true},f.catalog.settings().revision);assert.equal(f.catalog.publicCatalog().mostrar_destacados,true);});

test('precios separados: cuatro combinaciones web/PDF, elección obligatoria y sin cambios persistidos',async t=>{
  const seen=[];const f=await fixture(t,{pdfGenerator:async(s,o)=>{seen.push({s,o});return Buffer.from('%PDF-test');}}),c=f.client();await c.login();
  f.catalog.save(null,item('Con importe',{precio:10000}));f.catalog.save(null,item('Consultar'));
  for(const webPrices of [false,true]){
    f.catalog.updateSettings({mostrar_precios:webPrices},f.catalog.settings().revision);const before=f.catalog.settings();
    for(const includePrices of [false,true]){
      const r=await c.request('/api/admin/pdf',{method:'POST',body:{onlyInStock:false,includePrices,revision:before.revision}});
      assert.equal(r.status,200);assert.equal(seen.at(-1).o.includePrices,includePrices);
      assert.match(r.headers.get('content-disposition'),new RegExp(`${includePrices?'con':'sin'}-precios`));
      assert.ok(f.catalog.publicCatalog().items.every(p=>Object.hasOwn(p,'precio')===webPrices));
      assert.deepEqual(f.catalog.settings(),before);
    }
    for(const invalidPrice of [undefined,null,'true',1])assert.equal((await c.request('/api/admin/pdf',{method:'POST',body:{onlyInStock:false,includePrices:invalidPrice,revision:before.revision}})).status,422);
  }
});
test('ocho destacados como máximo, incluso con escritura directa por API',async t=>{const f=await fixture(t);const ids=[];for(let i=0;i<9;i++)ids.push(f.catalog.save(null,item('P'+i)).id);f.catalog.featured(ids.slice(0,8),f.catalog.settings().revision);assert.throws(()=>f.catalog.featured(ids,f.catalog.settings().revision),/ocho/);assert.throws(()=>f.catalog.save(ids[8],{destacado:true},f.catalog.get(ids[8]).version),/ocho/);f.catalog.featured([...ids.slice(0,7),ids[8]],f.catalog.settings().revision);assert.equal(f.catalog.publicCatalog().items.filter(p=>p.destacado).length,8);let p=f.catalog.get(ids[0]);f.catalog.save(p.id,{visible:false},p.version);assert.equal(f.catalog.publicCatalog().items.filter(p=>p.destacado).length,7);});
test('conflicto entre pestañas y rollback si falla el commit',async t=>{let fail=false;const f=await fixture(t,{fault:p=>{if(fail&&p==='beforeProductCommit')throw new Error('Fallo simulado');}});const p=f.catalog.save(null,item('Original'));f.catalog.save(p.id,{producto:'Nueva'},p.version);assert.throws(()=>f.catalog.save(p.id,{producto:'Vieja'},p.version),/otra ventana/);fail=true;assert.throws(()=>f.catalog.save(p.id,{producto:'No guardar'},p.version+1));assert.equal(f.catalog.get(p.id).producto,'Nueva');});
test('foto: metadatos, transparencia, dimensiones, idempotencia y recuperación',async t=>{const f=await fixture(t);const bytes=await photo();const a=await f.images.upload(bytes,'test-admin','test-upload-1');const b=await f.images.upload(bytes,'test-admin','test-upload-1');assert.equal(a.mediaId,b.mediaId);assert.equal(f.db.prepare('SELECT count(*) AS n FROM media').get().n,1);assert.equal(f.images.status('test-admin','test-upload-1').status,'ready');const meta=await sharp(f.images.file(a.mediaId,'master')).metadata();assert.equal(meta.hasAlpha,false);assert.equal(meta.exif,undefined);assert.equal(meta.width,800);assert.equal(meta.height,600);assert.equal((await sharp(f.images.file(a.mediaId,'thumb')).metadata()).width,320);await assert.rejects(f.images.upload(Buffer.from('diferente'),'test-admin','test-upload-1'),/otra foto/);let p=f.catalog.save(null,item('Con foto',{imagen_id:a.mediaId}));const next=await f.images.upload(bytes,'test-admin','test-upload-2');p=f.catalog.save(p.id,{imagen_id:next.mediaId},p.version);assert.equal(f.db.prepare('SELECT media_id FROM media_versions WHERE product_id=?').get(p.id).media_id,a.mediaId);p=f.catalog.save(p.id,{imagen_id:a.mediaId},p.version);assert.equal(p.imagen_id,a.mediaId);});
test('subida multipart con nombre sin extensión y fotos no publicadas privadas',async t=>{const f=await fixture(t),c=f.client(),guest=f.client();await c.login();const body=new FormData();body.append('foto',new Blob([await photo()],{type:'application/octet-stream'}),'foto áé sin extensión');const result=await c.request('/api/admin/media',{method:'POST',form:body,headers:{'Idempotency-Key':'multipart-prueba'}});assert.equal(result.status,200);const url=`/media/${result.data.mediaId}/web`;assert.equal((await guest.request(url)).status,404);assert.equal((await c.request(url)).status,200);let p=f.catalog.save(null,item('Visible',{imagen_id:result.data.mediaId}));assert.equal((await guest.request(url)).status,200);f.catalog.save(p.id,{visible:false},p.version);assert.equal((await guest.request(url)).status,404);});
test('archivos inválidos, excesivos y EXIF de orientación',async t=>{const f=await fixture(t);await assert.rejects(f.images.upload(Buffer.from('not an image'),'test-admin','bad-image-1'),/leer/);await assert.rejects(f.images.upload(Buffer.alloc(10*1024**2+1),'test-admin','big-image-1'),/10 MB/);const bytes=await sharp({create:{width:600,height:800,channels:3,background:'red'}}).withMetadata({orientation:6}).jpeg().toBuffer();const a=await f.images.upload(bytes,'test-admin','exif-image-1');const m=await sharp(f.images.file(a.mediaId,'master')).metadata();assert.equal(m.width,800);assert.equal(m.height,600);assert.equal(m.exif,undefined);});
test('fallo de disco en cada fase: no reemplaza foto publicada; reintento recupera',async t=>{let point=null;const f=await fixture(t,{fault:p=>{if(p===point)throw Object.assign(new Error('Disco lleno simulado'),{code:'ENOSPC'});}});const bytes=await photo();const original=await f.images.upload(bytes,'test-admin','original-photo');const p=f.catalog.save(null,item('Producto',{imagen_id:original.mediaId}));for(const step of ['afterStage','afterMaster','afterDerivatives','afterRename','afterMediaCommit']){point=step;await assert.rejects(f.images.upload(bytes,'test-admin','failure-'+step));assert.equal(f.catalog.get(p.id).imagen_id,original.mediaId);point=null;const recovered=await f.images.upload(bytes,'test-admin','failure-'+step);assert.equal(recovered.status,'ready');assert.equal(f.images.active.size,0);}});
test('derivado faltante se regenera; maestra faltante devuelve error',async t=>{const f=await fixture(t),a=await f.images.upload(await photo(),'test-admin','derive-photo');fs.unlinkSync(f.images.file(a.mediaId,'pdf'));assert.ok(fs.existsSync(await f.images.ensure(a.mediaId,'pdf')));fs.unlinkSync(f.images.file(a.mediaId,'pdf'));fs.unlinkSync(f.images.file(a.mediaId,'master'));await assert.rejects(f.images.ensure(a.mediaId,'pdf'),/Falta/);});
test('terminación abrupta real del proceso entre fases y recuperación tras reinicio',async t=>{const f=await fixture(t),bytes=await photo();const original=await f.images.upload(bytes,'test-admin','crash-original');const p=f.catalog.save(null,item('Sobrevive',{imagen_id:original.mediaId}));const file=path.join(f.cfg.dataDir,'input.png');fs.writeFileSync(file,bytes);for(const point of ['afterStage','afterMaster','afterDerivatives','afterRename','afterMediaCommit']){const child=spawnSync(process.execPath,['tests/integration/crash-worker.js',f.cfg.dataDir,point,file],{cwd:ROOT,encoding:'utf8'});assert.equal(child.status,81,child.stderr);assert.equal(f.catalog.get(p.id).imagen_id,original.mediaId);const recovered=await f.images.upload(bytes,'crash-admin','crash-'+point);assert.equal(recovered.status,'ready');assert.ok(fs.existsSync(f.images.file(recovered.mediaId,'pdf')));}});
test('limpieza protege archivados, historial, PDF activo y backup',async t=>{const f=await fixture(t),bytes=await photo(),m=[];for(let i=0;i<4;i++)m.push(await f.images.upload(bytes,'test-admin','clean-photo-'+i));let p=f.catalog.save(null,item('Producto',{imagen_id:m[0].mediaId}));p=f.catalog.save(p.id,{imagen_id:m[1].mediaId},p.version);f.catalog.archive(p.id,p.version);const release=f.images.pin([m[2].mediaId]);f.db.prepare('UPDATE media SET updated_at=?').run(Date.now()-2*86400000);f.db.prepare('INSERT INTO leases VALUES(?,NULL,?)').run('backup-test',Date.now()+60000);assert.equal(f.images.cleanup().paused,true);f.db.prepare('DELETE FROM leases WHERE id=?').run('backup-test');assert.equal(f.images.cleanup().removed,1);for(let i=0;i<3;i++)assert.ok(f.images.row(m[i].mediaId));release();assert.equal(f.images.cleanup().removed,1);});
test('100 reemplazos, cierre/reapertura y limpieza de archivos temporales',async t=>{const f=await fixture(t),bytes=await sharp({create:{width:32,height:48,channels:3,background:'blue'}}).png().toBuffer();let p=f.catalog.save(null,item('Ciclos'));for(let i=0;i<100;i++){const m=await f.images.upload(bytes,'test-admin','cycle-'+String(i).padStart(8,'0'));p=f.catalog.save(p.id,{imagen_id:m.mediaId},p.version);}assert.equal(f.db.prepare('SELECT count(*) AS n FROM media_versions').get().n,99);assert.equal(fs.readdirSync(path.join(f.cfg.dataDir,'staging')).length,0);assert.ok(fs.existsSync(f.images.file(p.imagen_id,'web')));const second=createApp(f.cfg);assert.equal(second.catalog.get(p.id).imagen_id,p.imagen_id);second.close();});
test('backup cifrado, hashes, restauración e integridad de fotos y precios',async t=>{const f=await fixture(t),a=await f.images.upload(await photo(),'test-admin','backup-photo');const p=f.catalog.save(null,item('Respaldo',{precio:456789,imagen_id:a.mediaId}));const key=randomBytes(32),destination=path.join(f.cfg.dataDir,'backup-output');const saved=await backup(f,f.cfg,{destination,key});assert.ok(!fs.existsSync(path.join(saved.path,'snapshot.sqlite')));const target=path.join(f.cfg.dataDir,'restored');await restore(saved.path,target,key);const restored=createApp({...f.cfg,dataDir:target});try{assert.equal(restored.catalog.get(p.id).precio,456789);assert.equal(hash(fs.readFileSync(restored.images.file(a.mediaId,'master'))),hash(fs.readFileSync(f.images.file(a.mediaId,'master'))));assert.equal(restored.db.pragma('integrity_check',{simple:true}),'ok');}finally{restored.close();}await assert.rejects(restore(saved.path,target,key),/vacía/);await assert.rejects(restore(saved.path,path.join(f.cfg.dataDir,'wrong-key'),randomBytes(32)));});
test('PDF exige sesión/revisión; sin productos no exporta; snapshot consistente y límite simultáneo',async t=>{let finish;const pending=new Promise(r=>finish=r);let captured;const f=await fixture(t,{pdfGenerator:async(snapshot)=>{captured=snapshot;await pending;return Buffer.from('%PDF-test');}}),c=f.client();await c.login();let r=await c.request('/api/admin/pdf',{method:'POST',body:{onlyInStock:false,includePrices:false,revision:f.catalog.settings().revision}});assert.equal(r.status,422);const p=f.catalog.save(null,item('PDF'));r=await c.request('/api/admin/pdf',{method:'POST',body:{onlyInStock:false,includePrices:false,revision:0}});assert.equal(r.status,409);const req=c.request('/api/admin/pdf',{method:'POST',body:{onlyInStock:false,includePrices:false,revision:f.catalog.settings().revision}});while(!captured)await new Promise(r=>setTimeout(r,5));f.catalog.save(p.id,{producto:'Cambio posterior'},p.version);r=await c.request('/api/admin/pdf',{method:'POST',body:{onlyInStock:false,includePrices:false,revision:f.catalog.settings().revision}});assert.equal(r.status,429);finish();r=await req;assert.equal(r.status,200);assert.equal(captured.items[0].producto,'PDF');assert.match(r.headers.get('cache-control'),/no-store/);assert.equal(f.db.prepare('SELECT count(*) AS n FROM leases').get().n,0);});
