import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {config} from '../server/config.js';
import {openDb} from '../server/db.js';
import {catalogService,defaults} from '../server/services/catalog.js';
import {imageService} from '../server/services/images.js';
const favorites=[['Brie','125 g','Cremoso, de corteza blanca y corazón suave. Emborg · Dinamarca.'],['Queso azul danés cremoso','100 g','Danablu Creamy: extra cremoso y suave. Emborg · Dinamarca.'],['Cheddar','150 g','Suave y fundente, el aliado de la cocina. Emborg.'],['Grana Padano','Pieza 1 kg aprox.','DOP, para rallar o en lascas. Zanetti · Italia.'],['Jamón serrano loncheado Gourmet','50 g','Loncheado, curado con paciencia. Arroyo Gourmet · España.'],['Chorizo extra loncheado Artesano','70 g','Chorizo extra loncheado. Arroyo Artesano · España.'],['Jamón cocido Castagna','Bloque 7.5 kg aprox.','Prosciutto cotto Castagna, el clásico italiano. Leoncini · Italia.'],['Old Amsterdam','Pieza','Gouda madurado de carácter intenso. Westland · Países Bajos.']];
export async function importCatalog(cfg){const db=openDb(cfg.dataDir);try{if(db.prepare("SELECT value FROM meta WHERE key='imported'").get())return {alreadyImported:true};if(db.prepare('SELECT count(*) AS n FROM products').get().n)throw new Error('La base ya tiene productos. No se sobrescribe.');const items=JSON.parse(await fs.readFile(path.join(cfg.root,'data/catalogo.json'),'utf8'));const catalog=catalogService(db),images=imageService(db,cfg);const prepared=[];
  for(const [i,p] of items.entries()){const bool=x=>{if(x==='SI')return true;if(x==='NO')return false;throw new Error('Estado inválido: '+x);};if(p.precio&&!/^\d+$/.test(p.precio))throw new Error('Precio ambiguo: '+p.producto);let media=null;if(p.imagen){if(path.basename(p.imagen)!==p.imagen)throw new Error('Imagen no local: '+p.imagen);const bytes=await fs.readFile(path.join(cfg.root,'assets/img/catalogo',p.imagen));media=(await images.upload(bytes,'migration','import-'+i)).mediaId;}const f=favorites.find(f=>f[0]===p.producto&&f[1]===p.presentacion);prepared.push({...defaults,producto:p.producto,categoria:p.categoria,marca:p.marca,origen:p.origen,presentacion:p.presentacion,notas:p.notas,precio:p.precio?Number(p.precio):null,por_kg:bool(p.por_kg),visible:bool(p.visible),stock:bool(p.stock),orden:i,imagen_id:media,resumen:f?.[2]||''});}
  db.transaction(()=>{const products=prepared.map(p=>catalog.save(null,p));const ids=favorites.map(f=>{const matches=products.filter(p=>p.producto===f[0]&&p.presentacion===f[1]);if(matches.length!==1)throw new Error('Favorito ambiguo: '+f[0]);return matches[0].id;});catalog.featured(ids,catalog.settings().revision);db.prepare("INSERT INTO meta VALUES('imported',?)").run(new Date().toISOString());}).immediate();return {products:prepared.length,photos:prepared.filter(p=>p.imagen_id).length,favorites:8};
}finally{db.close();}}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(await importCatalog(config()));
