import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import {randomBytes,randomUUID,createCipheriv,createDecipheriv} from 'node:crypto';
import Database from 'better-sqlite3';
import {hash,removeInside} from './images.js';
const seal=(bytes,key)=>{const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv);const encrypted=Buffer.concat([c.update(bytes),c.final()]);return Buffer.concat([iv,c.getAuthTag(),encrypted]);};
const unseal=(bytes,key)=>{const d=createDecipheriv('aes-256-gcm',key,bytes.subarray(0,12));d.setAuthTag(bytes.subarray(12,28));return Buffer.concat([d.update(bytes.subarray(28)),d.final()]);};
export function backupKey(cfg){if(process.env.BACKUP_KEY){const key=Buffer.from(process.env.BACKUP_KEY,'base64');if(key.length!==32)throw new Error('BACKUP_KEY debe contener 32 bytes en Base64.');return key;}if(cfg.production)throw new Error('Configurá BACKUP_KEY en producción.');const file=path.join(cfg.dataDir,'.backup-key');if(!fs.existsSync(file))fs.writeFileSync(file,randomBytes(32),{mode:0o600});return fs.readFileSync(file);}
export async function backup(ctx,cfg,{destination,key,now=new Date()}={}){
  key ||= backupKey(cfg);destination ||= process.env.BACKUP_DIR||path.join(cfg.dataDir,'backups');destination=path.resolve(destination);await fsp.mkdir(destination,{recursive:true});
  const id=now.toISOString().replace(/[:.]/g,'-')+'-'+randomUUID().slice(0,8),tmp=path.join(destination,'.partial-'+id),final=path.join(destination,id),lease='backup:'+id;await fsp.mkdir(tmp);ctx.db.prepare('INSERT INTO leases VALUES(?,NULL,?)').run(lease,Date.now()+3600000);
  let timer=setInterval(()=>ctx.db.prepare('UPDATE leases SET expires=? WHERE id=?').run(Date.now()+3600000,lease),60000);timer.unref();
  try{const snapshot=path.join(tmp,'snapshot.sqlite');await ctx.db.backup(snapshot);const db=new Database(snapshot);db.prepare('DELETE FROM sessions').run();db.prepare('DELETE FROM leases').run();const media=db.prepare("SELECT id FROM media WHERE status='ready'").all();const revision=db.prepare('SELECT revision FROM settings WHERE id=1').get().revision;db.close();const manifest={format:1,id,createdAt:now.toISOString(),revision,files:[]};
    const sources=[['catalog.sqlite',snapshot]];for(const m of media)for(const variant of ['master','thumb','web','pdf'])sources.push([`media/${m.id}/${variant}.jpg`,await ctx.images.ensure(m.id,variant)]);
    for(const [name,source] of sources){const bytes=await fsp.readFile(source);const encryptedName=String(manifest.files.length).padStart(5,'0')+'.enc';const encrypted=seal(bytes,key);await fsp.writeFile(path.join(tmp,encryptedName),encrypted);if(hash(unseal(await fsp.readFile(path.join(tmp,encryptedName)),key))!==hash(bytes))throw new Error('No coincide el respaldo: '+name);manifest.files.push({name,encryptedName,hash:hash(bytes),size:bytes.length});}
    await fsp.unlink(snapshot);for(const suffix of ['-wal','-shm'])await fsp.rm(snapshot+suffix,{force:true});await fsp.writeFile(path.join(tmp,'manifest.enc'),seal(Buffer.from(JSON.stringify(manifest)),key));await fsp.rename(tmp,final);return {path:final,files:manifest.files.length,revision};
  }finally{clearInterval(timer);ctx.db.prepare('DELETE FROM leases WHERE id=?').run(lease);if(fs.existsSync(tmp))removeInside(destination,tmp);}
}
export async function restore(source,destination,key){source=path.resolve(source);destination=path.resolve(destination);if(fs.existsSync(destination)&&fs.readdirSync(destination).length)throw new Error('La restauración requiere una carpeta vacía. Nunca sobrescribe la base activa.');const manifest=JSON.parse(unseal(await fsp.readFile(path.join(source,'manifest.enc')),key));if(manifest.format!==1||!Array.isArray(manifest.files))throw new Error('Formato de respaldo inválido.');const parent=path.dirname(destination),temp=path.join(parent,'.restore-'+randomUUID());await fsp.mkdir(temp,{recursive:true});try{for(const entry of manifest.files){if(!/^(catalog\.sqlite|media\/[a-f0-9-]{36}\/(master|thumb|web|pdf)\.jpg)$/.test(entry.name)||!/^\d{5}\.enc$/.test(entry.encryptedName))throw new Error('Ruta inválida en respaldo.');const bytes=unseal(await fsp.readFile(path.join(source,entry.encryptedName)),key);if(hash(bytes)!==entry.hash||bytes.length!==entry.size)throw new Error('Respaldo alterado o incompleto.');const target=path.join(temp,entry.name);await fsp.mkdir(path.dirname(target),{recursive:true});await fsp.writeFile(target,bytes);}const check=new Database(path.join(temp,'catalog.sqlite'));if(check.pragma('integrity_check',{simple:true})!=='ok')throw new Error('Base restaurada inválida.');check.close();if(fs.existsSync(destination))await fsp.rmdir(destination);await fsp.rename(temp,destination);return {files:manifest.files.length,revision:manifest.revision};}finally{if(fs.existsSync(temp))removeInside(parent,temp);}}
export function pruneBackups(destination,now=new Date()){const root=path.resolve(destination);if(!fs.existsSync(root))return;const dirs=fs.readdirSync(root,{withFileTypes:true}).filter(d=>d.isDirectory()&&/^\d{4}-\d{2}-\d{2}T/.test(d.name)&&fs.existsSync(path.join(root,d.name,'manifest.enc'))).map(d=>d.name).sort().reverse();const keep=new Set(),days=new Set(),weeks=new Set();for(const name of dirs){const day=name.slice(0,10),date=new Date(day+'T00:00:00Z');const monday=new Date(date);monday.setUTCDate(date.getUTCDate()-((date.getUTCDay()+6)%7));const week=monday.toISOString().slice(0,10);if(!days.has(day)&&days.size<7){days.add(day);keep.add(name);}if(!weeks.has(week)&&weeks.size<4){weeks.add(week);keep.add(name);}}for(const name of dirs)if(!keep.has(name))removeInside(root,path.join(root,name));}
