(() => {
  'use strict';
  const root=document.querySelector('[data-catalog]'),filters=document.querySelector('[data-filters]'),status=document.querySelector('[data-status]');
  const home=document.querySelector('[data-featured]');let items=[],category='';
  const normalize=s=>s.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase();
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  function card(p,isHome=false){const li=el('li',undefined,'product-card catalog-card'+(!p.stock?' is-nostock':''));const media=el('div',undefined,'product-media');const placeholder=()=>{media.querySelector('img')?.remove();media.append(el('span','Imagen próximamente','catalog-placeholder'));};if(p.imagen){const img=el('img');img.src=p.imagen;img.alt=p.producto;img.width=1000;img.height=1000;img.loading='lazy';img.onerror=placeholder;media.append(img);}else placeholder();if(!p.stock)media.append(el('span','Sin stock','badge-nostock'));li.append(media,el('h3',p.producto,'product-name'),el('p',p.presentacion,'catalog-presentation'),el('p',[p.marca,p.origen].filter(Boolean).join(' · '),'catalog-meta'));if(isHome&&p.resumen)li.append(el('p',p.resumen,'product-note'));else if(p.notas)li.append(el('p',p.notas,'product-note'));if(Object.hasOwn(p,'precio'))li.append(el('p',p.precio===null?'Consultar precio':`G$ ${new Intl.NumberFormat('es-PY').format(p.precio)}${p.por_kg?' / kg':''}`,'public-price'));const a=el('a','Consultar este producto','product-inquiry');a.href='mailto:jvanden@silospy.com,cecierbin@silospy.com?subject='+encodeURIComponent('Consulta: '+p.producto)+'&body='+encodeURIComponent(`Hola, me interesa ${p.producto}${p.presentacion?' ('+p.presentacion+')':''}. Quisiera consultar disponibilidad y condiciones. Gracias.`);li.append(a);return li;}
  function render(){root.replaceChildren();const q=normalize(document.querySelector('#catalog-search')?.value||'');const stock=document.querySelector('#catalog-stock')?.checked;const filtered=items.filter(p=>(!category||category===p.categoria)&&(!stock||p.stock)&&normalize(p.producto+' '+p.marca).includes(q));status.hidden=false;status.textContent=`${filtered.length} ${filtered.length===1?'producto':'productos'}`;if(!filtered.length){const empty=el('div',undefined,'catalog-empty');empty.append(el('p','No encontramos productos con esos filtros.'));const clear=el('button','Limpiar filtros','chip-btn');clear.onclick=()=>{category='';document.querySelector('#catalog-search').value='';document.querySelector('#catalog-stock').checked=false;renderFilters();render();};empty.append(clear);root.append(empty);return;}for(const cat of [...new Set(filtered.map(p=>p.categoria))]){const section=el('section',undefined,'catalog-group');section.append(el('h2',cat));const grid=el('ul',undefined,'catalog-grid');filtered.filter(p=>p.categoria===cat).forEach(p=>grid.append(card(p)));section.append(grid);root.append(section);}}
  function renderFilters(){filters.replaceChildren();for(const cat of ['',...new Set(items.map(p=>p.categoria))]){const b=el('button',cat||'Todas','chip-btn');b.type='button';b.setAttribute('aria-pressed',String(cat===category));b.onclick=()=>{category=cat;renderFilters();render();};filters.append(b);}}
  fetch('/api/catalogo',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(data=>{items=data.items;if(home){const chosen=items.filter(p=>p.destacado&&data.mostrar_destacados).sort((a,b)=>a.featuredOrder-b.featuredOrder).slice(0,8);home.replaceChildren(...chosen.map(p=>card(p,true)));if(!chosen.length)document.querySelector('#productos').hidden=true;}if(root){renderFilters();render();document.querySelector('#catalog-search').oninput=render;document.querySelector('#catalog-stock').onchange=render;}}).catch(()=>{if(status){status.hidden=false;status.textContent='No pudimos cargar el catálogo. Reintentá o escribinos por email.';}if(home)home.replaceChildren(el('p','No pudimos cargar los productos. Consultanos por email.'));});
})();
